environment: production
chdir: /home/ujjawal/espeak-http
address: 127.0.0.1
port: 4567
pid: /home/ujjawal/espeak-http/thin.pid
rackup: /home/ujjawal/espeak-http/config.ru
log: /home/ujjawal/espeak-http/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
